import { AlertTriangle, ArrowLeft, ShieldCheck } from "lucide-react";
import Link from "next/link";

import ApiNotice, { EmptyNotice } from "@/components/api/ApiNotice";
import {
  BADGE_LABEL,
  SESSION_STATE_LABEL,
  familyLabel,
  initials,
  scoreBand,
} from "@/lib/api/format";
import { buildOpening } from "@/lib/api/openings";
import { getRankedCandidates, getRole } from "@/lib/api/recruiter";

/**
 * Applicants to one opening, ranked under its own lens.
 *
 * The ranking comes from `GET /api/recruiter/candidates?role_id=`, which
 * re-weights evidence already collected — so this order is specific to this
 * opening, and the same people appear in a different order under another one.
 * That is the product, visible on a screen a recruiter actually uses.
 *
 * The list is the lens's cohort: candidates whose resume routed to its job
 * family, because those are the people its claim weights apply to. Everyone
 * else is one click away, and the page says so rather than quietly widening
 * the definition of "applicant".
 *
 * `why_ranked` replaces the old mock skill chips. It is generated by the
 * backend from stored rows with no model call, and it is the sentence that
 * turns a ranked list from an assertion into an explanation.
 */
export default async function ApplicantsPage({
  params,
}: {
  params: Promise<{ jobId: string }>;
}) {
  const { jobId } = await params;
  const [role, ranked] = await Promise.all([
    getRole(jobId),
    getRankedCandidates(jobId),
  ]);

  const back = (
    <Link href={`/recruiter/jobs/${jobId}`} className="recruiter-back">
      <ArrowLeft size={15} /> Back to the opening
    </Link>
  );

  if (!role.ok) {
    return (
      <main className="recruiter-page">
        {back}
        <ApiNotice error={role.error} what="this opening" />
      </main>
    );
  }
  if (!ranked.ok) {
    return (
      <main className="recruiter-page">
        {back}
        <ApiNotice error={ranked.error} what="the applicants" />
      </main>
    );
  }
  if (role.data === null) {
    return (
      <main className="recruiter-page">
        {back}
        <div className="api-notice">
          <AlertTriangle size={18} />
          <div>
            <b>No such opening.</b>
            <p>
              The API has no role lens with id <code>{jobId}</code>.
            </p>
          </div>
        </div>
      </main>
    );
  }

  const { role: lens, cohort } = buildOpening(role.data, ranked.data.candidates);
  const others = ranked.data.candidates.length - cohort.length;

  return (
    <main className="recruiter-page">
      {back}

      <div className="recruiter-heading">
        <div>
          <span className="eyebrow">
            APPLICANTS / {lens.title.toUpperCase()}
          </span>
          <h1>Applicant review</h1>
          <p>
            Ranked under this opening&apos;s own weights — a different opening
            puts the same people in a different order.
          </p>
        </div>
      </div>

      <div className="applicants-toolbar">
        <span className="applicant-count">
          {cohort.length}{" "}
          {cohort.length === 1 ? "applicant" : "applicants"} in{" "}
          {familyLabel(lens.job_family, lens.job_family_label)}
        </span>
        {others > 0 && (
          <Link
            href={`/recruiter/candidates?role_id=${encodeURIComponent(lens.id)}`}
            className="text-button"
          >
            {others} candidate{others === 1 ? "" : "s"} from other families are
            also ranked under this lens
          </Link>
        )}
      </div>

      {cohort.length === 0 ? (
        <EmptyNotice title="Nobody has routed to this job family yet.">
          <p>
            Onboard a candidate whose resume speaks this family&apos;s
            vocabulary and they appear here once they have answered.
          </p>
        </EmptyNotice>
      ) : (
        <div className="applicant-table">
          {cohort.map((candidate, index) => (
            <Link
              href={`/recruiter/candidates/${candidate.id}?role_id=${encodeURIComponent(lens.id)}`}
              className="applicant-row"
              key={candidate.id}
            >
              <span className="ranked-position">{index + 1}</span>
              <span className="avatar candidate-avatar">
                {initials(candidate.name)}
              </span>
              <span className="candidate-main">
                <b>
                  {candidate.name}
                  <em className={`badge-chip badge-${candidate.badge}`}>
                    {candidate.badge === "verified" && <ShieldCheck size={11} />}
                    {BADGE_LABEL[candidate.badge]}
                  </em>
                  {candidate.contradiction_count > 0 && (
                    <em className="badge-chip badge-flag">
                      <AlertTriangle size={11} />
                      {candidate.contradiction_count}
                    </em>
                  )}
                </b>
                <small>
                  {candidate.role ?? "Role not stated"}
                  {candidate.state
                    ? ` · ${SESSION_STATE_LABEL[candidate.state]}`
                    : ""}
                </small>
                {candidate.why_ranked && (
                  <span className="why-ranked">{candidate.why_ranked}</span>
                )}
              </span>
              <span className="score-pair">
                <span
                  className={`score-cell score-${scoreBand(candidate.competence_score)}`}
                >
                  <b>{candidate.competence_score}</b>
                  <small>competence</small>
                </span>
                <span className="score-cell muted">
                  <b>{candidate.role_coverage}%</b>
                  <small>coverage</small>
                </span>
              </span>
            </Link>
          ))}
        </div>
      )}
    </main>
  );
}
